### ISSUE TITLE
`kubectl gs get nodepools` panics on an AWS vintage installation - semver: Parse(): Version string empty

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1522]
```nohighlight
$ kuebctl gs --context gs-gorilla get nodepools -A

panic: semver: Parse(): Version string empty

goroutine 1 [running]:
github.com/blang/semver/v4.MustParse({0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/blang/semver/v4@v4.0.0/semver.go:363 +0x1e5
github.com/giantswarm/kubectl-gs/internal/feature.(*Service).Supports(0xc000ee18d0, {0x2da8098?, 0x2dd06ed?}, {0x0, 0x0})
	/home/runner/work/kubectl-gs/kubectl-gs/internal/feature/feature.go:41 +0x114
github.com/giantswarm/kubectl-gs/cmd/get/nodepools/provider.getAWSAutoscaling({0xc000d06b00?, 0x0?, 0xc000526fc0?, 0x0?}, 0x4abea68?)
	/home/runner/work/kubectl-gs/kubectl-gs/cmd/get/nodepools/provider/aws.go:95 +0x85
github.com/giantswarm/kubectl-gs/cmd/get/nodepools/provider.getAWSNodePoolRow({0xc000d06b00?, 0x0?, 0xc000526fc0?, 0x0?}, 0xc0007c7650?)
	/home/runner/work/kubectl-gs/kubectl-gs/cmd/get/nodepools/provider/aws.go:70 +0x199
github.com/giantswarm/kubectl-gs/cmd/get/nodepools/provider.GetAWSTable({0x323d5e0?, 0xc000c8f1d0?}, 0x2db9de6?)
	/home/runner/work/kubectl-gs/kubectl-gs/cmd/get/nodepools/provider/aws.go:49 +0x31d
github.com/giantswarm/kubectl-gs/cmd/get/nodepools.(*runner).printOutput(0xc000519f10, {0x323d5e0, 0xc000c8f1d0})
	/home/runner/work/kubectl-gs/kubectl-gs/cmd/get/nodepools/printer.go:31 +0x29a
github.com/giantswarm/kubectl-gs/cmd/get/nodepools.(*runner).run(0xc000519f10, {0x325b7f0, 0xc000120000}, 0x0?, {0xc0003aa500, 0x0, 0x0?})
	/home/runner/work/kubectl-gs/kubectl-gs/cmd/get/nodepools/runner.go:99 +0x33a
github.com/giantswarm/kubectl-gs/cmd/get/nodepools.(*runner).Run(0x0?, 0x0?, {0xc0003aa500?, 0x0?, 0x0?})
	/home/runner/work/kubectl-gs/kubectl-gs/cmd/get/nodepools/runner.go:41 +0x3e
github.com/spf13/cobra.(*Command).execute(0xc000974f00, {0xc0003aa4f0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc00031a280)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.mainE({0xc000bbff70?, 0x1005ef9?})
	/home/runner/work/kubectl-gs/kubectl-gs/main.go:80 +0x173
main.main()
	/home/runner/work/kubectl-gs/kubectl-gs/main.go:27 +0x2b
```

**Comment by marians** [comment]
Assigning to phoenix based on the provider

**Comment by whites11** [comment]
TBH this is not a provider-specific problem. Kubectl-gs needed some value checking rather than relying on a value being present at all times with no exception, never being wrong etc.

Anywy here's the PR https://github.com/giantswarm/kubectl-gs/pull/933
